"""
Django settings for proyecto_manhattan project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

import dj_database_url
from dotenv import load_dotenv

# Cargar .env SOLO en local (si existe)
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

# =========================
# BASE
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SECURITY / ENV
# =========================
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-key")
DEBUG = os.environ.get("DEBUG", "1") == "1"

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

# =========================
# HOSTS / CSRF
# =========================
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# =========================
# APPS
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "asistencias",

    # ✅ Anti fuerza bruta
    "axes",
]

# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "asistencias.middleware.ClearAxesUnlockAtMiddleware",  # ✅ limpia axes_unlock_at
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ✅ Axes (después de AuthenticationMiddleware)
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "proyecto_manhattan.urls"

# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "proyecto_manhattan.wsgi.application"

# =========================
# DATABASE
# =========================
# ✅ Para evitar que “cambie solo” a SQLite, lo hacemos explícito:
# - Por defecto: PostgreSQL (DATABASE_URL obligatorio)
# - Si quieres SQLite local: exporta USE_SQLITE=1
USE_SQLITE = os.environ.get("USE_SQLITE", "0") == "1"
DATABASE_URL = os.environ.get("DATABASE_URL")

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    if not DATABASE_URL:
        raise RuntimeError(
            "❌ DATABASE_URL no está definido.\n"
            "✅ Estás por usar SQLite sin querer.\n"
            "➡️ Solución: define DATABASE_URL (PostgreSQL) o usa USE_SQLITE=1."
        )

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,  # en producción True; en local normalmente False
        )
    }

# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 10}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = "es-pe"
TIME_ZONE = "America/Lima"
USE_I18N = True
USE_TZ = True

# =========================
# STATIC FILES
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# LOGIN / LOGOUT
# =========================
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "post_login"
LOGOUT_REDIRECT_URL = "login"

# =========================
# AXES (bloqueo fuerza bruta)
# =========================
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_RESET_ON_SUCCESS = True

AXES_LOCKOUT_CALLABLE = "asistencias.axes.lockout"
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False

# Render/proxy: toma IP real del cliente
AXES_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
]
AXES_PROXY_ORDER = "left-most"

# =========================
# COOKIES / SECURITY
# =========================
# Mantener sesión aunque se cierre el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Duración de sesión (30 días)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    REFERRER_POLICY = "strict-origin-when-cross-origin"

    # HSTS: cuando estés 100% seguro, sube esto a 31536000
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# =========================
# LOGGING (silenciar Axes)
# =========================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "null": {"class": "logging.NullHandler"},
    },
    "loggers": {
        # ✅ silencia módulos de axes
        "axes": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
        "axes.handlers.database": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
        "axes.middleware": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
        "axes.signals": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
        "axes.backends": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},

        # (Opcional) quita logs GET/POST del runserver
        # "django.server": {"handlers": ["null"], "level": "CRITICAL", "propagate": False},
    },
}
