# Generated by Django 5.2.10 on 2026-02-08 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(max_length=120),
        ),
    ]
