# Generated by Django 5.2.10 on 2026-02-10 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_remove_asistencia_estado_remove_asistencia_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['profesor', 'fecha'], name='asistencias_profeso_c35b35_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('profesor', 'fecha', 'tipo'), name='uniq_profesor_fecha_tipo'),
        ),
    ]
