# Generated by Django 5.2.10 on 2026-02-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_asistencia_fecha_asistencia_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
