# Generated by Django 5.2.10 on 2026-02-11 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_profesor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('DM', 'Descanso médico'), ('C', 'Comisión / Encargo'), ('P', 'Permiso'), ('O', 'Otro')], default='DM', max_length=2)),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='asistencias.profesor')),
            ],
            options={
                'ordering': ['-fecha', 'profesor__apellidos', 'profesor__nombres'],
                'indexes': [models.Index(fields=['fecha', 'profesor'], name='asistencias_fecha_5f0741_idx')],
                'constraints': [models.UniqueConstraint(fields=('profesor', 'fecha'), name='uniq_justificacion_profesor_fecha')],
            },
        ),
    ]
