# Generated by Django 5.2.10 on 2026-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0005_justificacionasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='motivo',
            field=models.CharField(blank=True, choices=[('DM', 'Descanso médico'), ('C', 'Comisión / Encargo'), ('P', 'Permiso'), ('O', 'Otro')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('J', 'Justificación')], default='E', max_length=1),
        ),
    ]
