# Generated by Django 5.2.10 on 2026-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0006_asistencia_detalle_asistencia_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacionasistencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/'),
        ),
    ]
