# Generated by Django 5.2.10 on 2026-02-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_justificacionasistencia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/'),
        ),
    ]
