# Generated by Django 5.2.10 on 2026-02-15 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0008_alter_justificacionasistencia_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='justificacionasistencia',
            options={'ordering': ['-fecha', 'profesor__apellidos', 'profesor__nombres'], 'verbose_name': 'Justificación', 'verbose_name_plural': 'Justificaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='motivo',
            field=models.CharField(blank=True, choices=[('DM', 'Descanso médico'), ('C', 'Comisión / Encargo'), ('P', 'Permiso'), ('O', 'Otro')], default='', max_length=2, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('J', 'Justificación')], default='E', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='User agent'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/', verbose_name='Archivo (PDF)'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='asistencias.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='tipo',
            field=models.CharField(choices=[('DM', 'Descanso médico'), ('C', 'Comisión / Encargo'), ('P', 'Permiso'), ('O', 'Otro')], default='DM', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=120, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='condicion',
            field=models.CharField(max_length=20, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(max_length=120, verbose_name='Nombres'),
        ),
    ]
