# Generated by Django 5.2.10 on 2026-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0009_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('J', 'Justificación')], default='E', max_length=1, verbose_name='Tipo'),
        ),
    ]
