# Generated by Django 5.2.10 on 2026-02-26 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0010_alter_asistencia_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_intentado', models.CharField(blank=True, default='', max_length=150)),
                ('exito', models.BooleanField(default=False)),
                ('fecha_hora_servidor', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_cliente', models.CharField(blank=True, default='', max_length=60)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('precision_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_geo', models.CharField(blank=True, default='', max_length=50)),
                ('permiso_geo', models.CharField(blank=True, default='', max_length=20)),
                ('device_info', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_evidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de login',
                'verbose_name_plural': 'Evidencias de login',
                'ordering': ['-fecha_hora_servidor'],
            },
        ),
    ]
