# Generated by Django 5.2.10 on 2026-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0011_loginevidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacionasistencia',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='justificaciones/%Y/%m/', verbose_name='Archivo (PDF)'),
        ),
    ]
