# Generated by Django 5.2.10 on 2026-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0012_alter_justificacionasistencia_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('HUELGA', 'Huelga'), ('PARO', 'Paro de transportistas'), ('SUSPENSION', 'Suspensión de actividades'), ('REMOTO', 'Trabajo remoto institucional'), ('NO_LABORABLE', 'No laborable'), ('OTRO', 'Otro')], default='FERIADO', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Día especial',
                'verbose_name_plural': 'Días especiales',
                'ordering': ['-fecha'],
            },
        ),
    ]
