# Generated by Django 5.2.10 on 2026-04-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0013_diaespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('TC', 'Tiempo completo'), ('TP', 'Tiempo parcial')], default='', max_length=2, verbose_name='Tipo de jornada'),
        ),
    ]
