# Generated by Django 5.2.10 on 2026-04-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0014_profesor_activo_profesor_tipo_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('TC', 'Tiempo completo'), ('DE', 'Dedicación exclusiva'), ('TP', 'Tiempo parcial')], default='', max_length=2, verbose_name='Dedicación horaria'),
        ),
    ]
