# Generated by Django 5.2.10 on 2026-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0015_alter_profesor_tipo_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
